HuynhDatHung_Lab456/Models/Courses.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HuynhDatHung_Lab456.Models
{
    public class Courses
    {
        public int Id { get; set; }

        public bool IsCanceled { get; set; }
        public ApplicationUser Lecturer { get; set; }
        [Required]
        public string LecturerId { get; set; }
        [Required]
        [StringLength(255)]  
        public string Place { get; set; }
        public DateTime DateTime{get;set;}
        public Category Category { get; set; }
        [Required]
        public byte CategoryId { get; set; }


    }



}

HuynhDatHung_Lab456/ViewModels/CourseViewModel.cs
using HuynhDatHung_Lab456.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace HuynhDatHung_Lab456.ViewModels
{
    public class CourseViewModel

    {
        public int Id { get; set; }
        [Required]
        public string Place { get; set; }


        [Required]
        [FutureDate]
        public string Date { get; set; }
        [Required]
        [ValidTime]
        public string Time { get; set; }
        [Required]
        public Byte Category { get; set; }
        public IEnumerable<Category> Categories { get; set; }
        public DateTime GetDateTime()
        {
            return DateTime.Parse(string.Format("{0} {1}", Date, Time));
        }


        public string Heading { get; set; }
        public string Action
        {
            get { return (Id != 0) ? "Update" : "Create"; }
        }
    }



}

HuynhDatHung_Lab456/Controllers/Api/CoursesController.cs
using HuynhDatHung_Lab456.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace HuynhDatHung_Lab456.Controllers.Api
{
    public class CoursesController : ApiController
    {
        public ApplicationDbContext _dbContext { get; set; }
        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }

        [HttpDelete]
        public IHttpActionResult Cancel(int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);
            if (course.IsCanceled)
                return NotFound();
            course.IsCanceled = true;
            _dbContext.SaveChanges();
            return Ok();
        }

    }
}

HuynhDatHung_Lab456/Controllers/CourseController.cs
using HuynhDatHung_Lab456.Models;
using HuynhDatHung_Lab456.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HuynhDatHung_Lab456.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public CourseController()
        {
            _dbContext = new ApplicationDbContext();  
        }
        // GET: Courses
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(CourseViewModel viewModel)
        {
            //var viewModel = new CourseViewModel
            //{
            //    Categories = _dbContext.Categories.ToList()

            //};
            //return View(viewModel);
            if(!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Courses
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime = viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.Place

            };
            _dbContext.Courses.Add(course);
            _dbContext.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Attending()
        {

            var userId = User.Identity.GetUserId();

            var courses = _dbContext.Attendances.Where(a => a.AttendeeId == userId)
                .Select(a => a.Course)
                .Include(l => l.Lecturer)
                .Include(l => l.Category)
                .ToList();



            var viewModel = new CoursesViewModel
            {
                UpcomingCourses = courses,
                ShowAction = User.Identity.IsAuthenticated
            };


            return View(viewModel);
        }
        [Authorize]
        public ActionResult Mine()
        {
            var UserId = User.Identity.GetUserId();
            var courses = _dbContext.Courses.Where(c => c.LecturerId == UserId && c.DateTime>DateTime.Now)
               
               .Include(l => l.Lecturer)
               .Include(l => l.Category)
               .ToList();
            return View(courses);
        }


        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList(),
                Heading="Add Course"

            };
            return View(viewModel);
        }


        [Authorize]
        public ActionResult Edit(int id)
        {
            var userId = User.Identity.GetUserId();
            var course = _dbContext.Courses.Single(c => c.Id == id && c.LecturerId == userId);

            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList(),
                Date = course.DateTime.ToString("dd/M/yyyy"),
                Time = course.CategoryId.ToString(),
                Place = course.Place,
                 Heading = "Add Course",
                 Id=course.Id

            };
            return View("Create", viewModel);
        }




    }



}

HuynhDatHung_Lab456/Views/Course/Attending.cshtml
@model HuynhDatHung_Lab456.ViewModels.CoursesViewModel
@{
    ViewBag.Title = "Attending";
    Layout = "~/Views/Shared/_Layout.csthml";
}

<h2>Attending</h2>

<div class="row">
    <ul>
        @foreach (var course in Model.UpcomingCourses)
        {

            <li>
                <div class="date">
                    @course.DateTime.ToString("MM")

                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")


                </div>

                <div class="details">
                    <span class="lecturer">
                        @course.Lecturer.Name
                        if(Model.ShowAction)
                        {
                        <button class="btn btn-default btn-sm js-toggle-follow" data-user-id="@course.LecturerId">Follow</button>
                        }
                    </span>
                    <span class="category">
                        @course.Category.Name
                        if(Model.ShowAction)
                        {
                        <button data-course-id="@course.Id" class="btn btn-default btn-sm js-toggle-attendance">Going</button>
                        }
                    </span>
                </div>
            </li>
        }
    </ul>
</div>

HuynhDatHung_Lab456/Views/Course/Create.cshtml
@model HuynhDatHung_Lab456.ViewModels.CourseViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create</h2>
    @*<form>
        <div class="form-group">
            @Html.LabelFor(m => m.Place)
            @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Time)
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Category)
            @Html.DropDownListFor(m => m.Category, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
        </div>
        <button type="submit" value="Save" class="btn btn-primary">Save</button>

 </form>*@
@using (Html.BeginForm(Model.Action, "Course"))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.Place)
            @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
            @Html.ValidationMessageFor(m=>m.Place)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Time)
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Time)
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Category)
            @Html.DropDownListFor(m => m.Category, new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Category)
        </div>

        <button type="submit" value="Save" class="btn btn-primary">Save</button>
      
    


}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval");
    }

HuynhDatHung_Lab456/Views/Course/Mine.cshtml
@model IEnumerable<HuynhDatHung_Lab456.Models.Courses>
@{
    ViewBag.Title = "Mine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mine</h2>

<ul class="course">
    @foreach(var course in Model)
    {
        <li>
            <div class="date">
                <div class="month">
                    @course.DateTime.ToString("MM")
                </div>
                <div class="day">
                    @course.DateTime.ToString("dd")
                </div>
            </div>
            <div class="details">
                <span class="lecturer">
                    @course.Lecturer.Name
                </span>
                <span class="category">
                    @course.Category.Name
                </span>

            </div>
            <div class="action">
                <a href="@Url.Action("Edit","Courses",new {id=course.Id })">Edit</a>

                <a href="#"class="js-cancel-course"data-course-id="@course.Id">Cancel</a>


            </div>
        </li>
    }
</ul>
@section scripts
{
    <script>
        $(document).ready(function () {
            $(".js-cancel-course").click(function (e)){
                e.preventDefaut();
                var links = $(e.target);
                bootbox.confirm("Are you sure to cancel", function () {
                    $.ajax{
                        URL: "/api.courses" + link.attr("data-course-id"),
                            method: "DELETE"
                    })
                    .done(function () {
                        link.parents("li").fadeOut(function){
                            $(this).remove();
                        });
            })
            .fail(function () {
                alert("something failed!");
            });
                });
            });
        });



    </script>
    
    
    
    }